### ISSUE TITLE
Torrent protocol encryption

### ISSUE THREAD

**Issue by Zophar78** [steeve/plugin.video.pulsar#132]
Would be a useful feature (Disabled, Enabled and Forced).
Is there a chance you'll add it in the future?

**Comment by Zophar78** [comment]
Hum... https://github.com/steeve/torrent2http is the pulsard process?
According to the source encryption is "enabled" by default right?
In any case still a good feature to add to settings.

**Comment by steeve** [comment]
It is not the Pulsard sources, but encryption is on require by default yes.
Not being able to change that is by design so that people don't shoot
themselves in the foot.

On Sunday, April 12, 2015, Pierre Hanselmann <notifications@github.com>
wrote:

> Hum... https://github.com/steeve/torrent2http is the pulsard process?
> According to the source encryption is "enabled" by default right?
> In any case still a good feature to add to settings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steeve/plugin.video.pulsar/issues/132#issuecomment-91936165>
> .
>


-- 
Steeve Morin
twitter.com/steeve
github.com/steeve
linkd.in/smorin

**Comment by prilly** [comment]
Probably why openssl is a dependency
