### ISSUE TITLE
.

### ISSUE THREAD

**Issue by nigelpatsmith** [steeve/plugin.video.pulsar#134]

**Comment by lemonlee** [comment]
More info (from #136): 

Pulsar (like other torrent clients) relies on others being able to directly connect with it through an incoming port to send content. Most VPN provider NAT their connections meaning their is no full route to the IP address that the VPN provider gives you. Because of this, some VPN providers (eg PIA) allow you to request an incoming port. The problem is in the case of PIA, that the incoming port is random, and you can't request a specific port. So to have Pulsar get to good speeds, you have to be able to set that port that Pia give you into pulsar.
